CREATE TABLE IF NOT EXISTS crm_team (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  team_name VARCHAR(64) NOT NULL,
  supervisor_admin_id BIGINT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  update_by VARCHAR(64) NULL,
  KEY idx_supervisor_admin_id (supervisor_admin_id),
  KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM team';

CREATE TABLE IF NOT EXISTS crm_employee_profile (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  admin_id BIGINT NOT NULL,
  employee_name VARCHAR(64) NOT NULL,
  phone VARCHAR(32) NULL,
  team_id BIGINT NULL,
  crm_role VARCHAR(32) NOT NULL DEFAULT 'OPERATOR',
  daily_claim_limit INT NOT NULL DEFAULT 50,
  assign_weight INT NOT NULL DEFAULT 1,
  status TINYINT NOT NULL DEFAULT 1,
  data_scope VARCHAR(32) NOT NULL DEFAULT 'SELF',
  remark VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  update_by VARCHAR(64) NULL,
  UNIQUE KEY uk_admin_id (admin_id),
  KEY idx_team_id (team_id),
  KEY idx_crm_role (crm_role),
  KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM employee profile';

CREATE TABLE IF NOT EXISTS crm_customer (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  customer_name VARCHAR(64) NOT NULL,
  mobile VARCHAR(32) NOT NULL,
  mobile_md5 VARCHAR(64) NULL,
  crm_inst_id BIGINT NULL,
  crm_inst_code VARCHAR(64) NULL,
  crm_inst_name VARCHAR(128) NULL,
  source_inst_id BIGINT NULL,
  source_inst_code VARCHAR(64) NULL,
  source_inst_name VARCHAR(128) NULL,
  product_id BIGINT NULL,
  product_name VARCHAR(128) NULL,
  source_order_no VARCHAR(64) NULL,
  source_collision_no VARCHAR(64) NULL,
  id_card VARCHAR(64) NULL,
  city VARCHAR(64) NULL,
  age INT NULL,
  gender VARCHAR(16) NULL,
  occupation VARCHAR(64) NULL,
  monthly_income DECIMAL(12,2) NULL,
  has_social_security TINYINT NULL,
  has_housing_fund TINYINT NULL,
  has_house TINYINT NULL,
  has_car TINYINT NULL,
  sesame_score INT NULL,
  credit_card_status VARCHAR(64) NULL,
  loan_amount DECIMAL(14,2) NULL,
  loan_purpose VARCHAR(128) NULL,
  expected_term VARCHAR(64) NULL,
  customer_source VARCHAR(64) NULL,
  channel_code VARCHAR(64) NULL,
  owner_admin_id BIGINT NULL,
  owner_name VARCHAR(64) NULL,
  team_id BIGINT NULL,
  customer_status VARCHAR(64) NOT NULL DEFAULT 'UNFOLLOWED',
  loan_intention VARCHAR(64) NOT NULL DEFAULT 'UNCONFIRMED',
  quality_star INT NOT NULL DEFAULT 3,
  follow_count INT NOT NULL DEFAULT 0,
  last_follow_time DATETIME NULL,
  next_follow_time DATETIME NULL,
  last_follow_remark VARCHAR(1024) NULL,
  is_allocated TINYINT NOT NULL DEFAULT 0,
  is_called TINYINT NOT NULL DEFAULT 0,
  is_duplicate TINYINT NOT NULL DEFAULT 0,
  is_valid TINYINT NOT NULL DEFAULT 1,
  wechat_added TINYINT NOT NULL DEFAULT 0,
  need_recall TINYINT NOT NULL DEFAULT 0,
  is_deal TINYINT NOT NULL DEFAULT 0,
  is_rejected TINYINT NOT NULL DEFAULT 0,
  is_key_customer TINYINT NOT NULL DEFAULT 0,
  in_public_pool TINYINT NOT NULL DEFAULT 1,
  public_pool_reason VARCHAR(64) NULL,
  wage_payment_type VARCHAR(64) NULL,
  social_security_status VARCHAR(64) NULL,
  housing_fund_status VARCHAR(64) NULL,
  house_status VARCHAR(64) NULL,
  car_status VARCHAR(64) NULL,
  insurance_status VARCHAR(64) NULL,
  credit_status VARCHAR(64) NULL,
  has_overdue TINYINT NULL,
  current_debt DECIMAL(14,2) NULL,
  has_credit_card TINYINT NULL,
  has_online_loan TINYINT NULL,
  acceptable_rate DECIMAL(8,4) NULL,
  urgent_money TINYINT NULL,
  remark VARCHAR(1024) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  update_by VARCHAR(64) NULL,
  KEY idx_mobile (mobile),
  KEY idx_mobile_md5 (mobile_md5),
  KEY idx_crm_inst_mobile_md5 (crm_inst_id, mobile_md5),
  KEY idx_crm_inst_id (crm_inst_id),
  KEY idx_source_inst_id (source_inst_id),
  KEY idx_product_id (product_id),
  KEY idx_source_order_no (source_order_no),
  KEY idx_source_collision_no (source_collision_no),
  KEY idx_owner_admin_id (owner_admin_id),
  KEY idx_team_id (team_id),
  KEY idx_status (customer_status),
  KEY idx_intention (loan_intention),
  KEY idx_quality_star (quality_star),
  KEY idx_next_follow_time (next_follow_time),
  KEY idx_public_pool (in_public_pool),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM customer lead';

CREATE TABLE IF NOT EXISTS crm_institution_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  inst_id BIGINT NOT NULL,
  inst_code VARCHAR(64) NOT NULL,
  inst_name VARCHAR(128) NOT NULL,
  platform_inst_id BIGINT NULL,
  platform_inst_code VARCHAR(64) NULL,
  platform_inst_name VARCHAR(128) NULL,
  crm_inst_id BIGINT NULL,
  crm_inst_code VARCHAR(64) NULL,
  crm_inst_name VARCHAR(128) NULL,
  auto_push TINYINT NOT NULL DEFAULT 1,
  auto_assign TINYINT NOT NULL DEFAULT 0,
  owner_admin_id BIGINT NULL,
  owner_name VARCHAR(64) NULL,
  team_id BIGINT NULL,
  customer_source VARCHAR(64) NOT NULL DEFAULT 'CRM_API',
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  update_by VARCHAR(64) NULL,
  UNIQUE KEY uk_inst_id (inst_id),
  KEY idx_inst_code (inst_code),
  KEY idx_platform_inst_id (platform_inst_id),
  KEY idx_crm_inst_id (crm_inst_id),
  KEY idx_owner_admin_id (owner_admin_id),
  KEY idx_team_id (team_id),
  KEY idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM institution binding config';

CREATE TABLE IF NOT EXISTS crm_follow_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  customer_id BIGINT NOT NULL,
  customer_name VARCHAR(64) NOT NULL,
  mobile VARCHAR(32) NULL,
  follower_admin_id BIGINT NOT NULL,
  follower_name VARCHAR(64) NOT NULL,
  team_id BIGINT NULL,
  follow_method VARCHAR(32) NOT NULL DEFAULT 'PHONE',
  follow_result VARCHAR(64) NULL,
  loan_intention VARCHAR(64) NULL,
  quality_star INT NULL,
  customer_status VARCHAR(64) NULL,
  remark VARCHAR(1024) NULL,
  follow_time DATETIME NOT NULL,
  next_follow_time DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_by VARCHAR(64) NULL,
  KEY idx_customer_id (customer_id),
  KEY idx_follower_admin_id (follower_admin_id),
  KEY idx_team_id (team_id),
  KEY idx_follow_time (follow_time),
  KEY idx_next_follow_time (next_follow_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM follow record';

CREATE TABLE IF NOT EXISTS crm_assignment_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  customer_id BIGINT NOT NULL,
  customer_name VARCHAR(64) NOT NULL,
  from_admin_id BIGINT NULL,
  from_admin_name VARCHAR(64) NULL,
  to_admin_id BIGINT NOT NULL,
  to_admin_name VARCHAR(64) NOT NULL,
  assigner_admin_id BIGINT NOT NULL,
  assigner_name VARCHAR(64) NOT NULL,
  assign_mode VARCHAR(32) NOT NULL DEFAULT 'MANUAL',
  remark VARCHAR(512) NULL,
  assigned_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_by VARCHAR(64) NULL,
  KEY idx_customer_id (customer_id),
  KEY idx_to_admin_id (to_admin_id),
  KEY idx_assigner_admin_id (assigner_admin_id),
  KEY idx_assigned_at (assigned_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM assignment record';

CREATE TABLE IF NOT EXISTS crm_public_pool_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  customer_id BIGINT NOT NULL,
  customer_name VARCHAR(64) NOT NULL,
  previous_owner_admin_id BIGINT NULL,
  previous_owner_name VARCHAR(64) NULL,
  operator_admin_id BIGINT NOT NULL,
  operator_name VARCHAR(64) NOT NULL,
  reason VARCHAR(64) NOT NULL,
  action_type VARCHAR(32) NOT NULL,
  remark VARCHAR(512) NULL,
  action_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_by VARCHAR(64) NULL,
  KEY idx_customer_id (customer_id),
  KEY idx_operator_admin_id (operator_admin_id),
  KEY idx_action_type (action_type),
  KEY idx_action_at (action_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM public pool record';

CREATE TABLE IF NOT EXISTS crm_rule_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  rule_code VARCHAR(64) NOT NULL,
  rule_name VARCHAR(128) NOT NULL,
  rule_value VARCHAR(256) NOT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  remark VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_by VARCHAR(64) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  update_by VARCHAR(64) NULL,
  UNIQUE KEY uk_rule_code (rule_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='CRM rule config';

INSERT IGNORE INTO crm_rule_config(rule_code, rule_name, rule_value, remark)
VALUES
('FIRST_FOLLOW_RECLAIM_DAYS', 'first follow reclaim days', '3', 'customer not followed in 3 days enters public pool'),
('REFOLLOW_REMIND_DAYS', 'refollow remind days', '7', 'customer not followed in 7 days should be reminded'),
('NO_EFFECTIVE_FOLLOW_RECLAIM_DAYS', 'no effective follow reclaim days', '15', 'customer without effective follow in 15 days enters public pool'),
('DAILY_CLAIM_LIMIT', 'daily claim limit', '50', 'default claim limit per operator'),
('HIGH_QUALITY_MIN_STAR', 'high quality min star', '4', '4 and 5 star customer requires supervisor assignment');
