CREATE TABLE IF NOT EXISTS `collision_record` (
  `id` BIGINT PRIMARY KEY COMMENT 'Snowflake ID',
  `collision_no` VARCHAR(32) NOT NULL UNIQUE COMMENT 'Collision record number',
  `channel_id` BIGINT NOT NULL COMMENT 'Channel ID',
  `channel_code` VARCHAR(32) DEFAULT NULL COMMENT 'Channel code snapshot',
  `inst_id` BIGINT DEFAULT NULL COMMENT 'Matched institution ID',
  `inst_code` VARCHAR(32) DEFAULT NULL COMMENT 'Matched institution code snapshot',
  `product_id` BIGINT DEFAULT NULL COMMENT 'Matched product ID',
  `product_name_snapshot` VARCHAR(128) DEFAULT NULL COMMENT 'Matched product name snapshot',
  `trace_id` VARCHAR(64) NOT NULL COMMENT 'Trace ID',
  `phone_md5` CHAR(32) NOT NULL COMMENT 'Phone MD5',
  `phone_enc` VARCHAR(128) NOT NULL COMMENT 'Encrypted phone',
  `id_card_enc` VARCHAR(256) NOT NULL COMMENT 'Encrypted ID card',
  `user_name` VARCHAR(64) NOT NULL COMMENT 'Encrypted user name',
  `user_name_md5` CHAR(32) DEFAULT NULL COMMENT 'Name MD5 for exact search',
  `age` TINYINT NOT NULL COMMENT 'Age',
  `city_code` VARCHAR(8) NOT NULL COMMENT 'City code',
  `work_city` VARCHAR(64) DEFAULT NULL COMMENT 'Working city',
  `gender` TINYINT DEFAULT NULL COMMENT 'Gender',
  `profession` TINYINT DEFAULT NULL COMMENT 'Profession',
  `zhima` INT DEFAULT NULL COMMENT 'Zhima score',
  `house` TINYINT DEFAULT NULL COMMENT 'House status',
  `vehicle` TINYINT DEFAULT NULL COMMENT 'Vehicle status',
  `vehicle_status` VARCHAR(32) DEFAULT NULL COMMENT 'Vehicle running status',
  `vehicle_value` VARCHAR(64) DEFAULT NULL COMMENT 'Vehicle value',
  `provident_fund` TINYINT DEFAULT NULL COMMENT 'Provident fund status',
  `social_security` TINYINT DEFAULT NULL COMMENT 'Social security status',
  `commercial_insurance` TINYINT DEFAULT NULL COMMENT 'Commercial insurance status',
  `overdue` TINYINT DEFAULT NULL COMMENT 'Overdue status',
  `loan_amount` INT DEFAULT NULL COMMENT 'Requested loan amount',
  `loan_time` INT DEFAULT NULL COMMENT 'Loan term',
  `customer_level` VARCHAR(32) DEFAULT NULL COMMENT 'Customer level',
  `device_ip` VARCHAR(45) DEFAULT NULL COMMENT 'Device IP',
  `collision_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 matched, 9 rejected',
  `reject_reason` VARCHAR(255) DEFAULT NULL COMMENT 'Failure reason',
  `settlement_price` DECIMAL(10,2) DEFAULT NULL COMMENT 'Matched settlement price',
  `ext_json` JSON DEFAULT NULL COMMENT 'Future compatibility extension',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_collision_phone` (`phone_md5`, `created_at`),
  INDEX `idx_collision_channel_time` (`channel_id`, `created_at`),
  INDEX `idx_collision_status_time` (`collision_status`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Collision record';
